### ISSUE TITLE
[to-html cmd] Absolute paths from a local disk in a HTML report

### ISSUE THREAD

**Issue by shikari-ac** [scan-io-git/scan-io#95]
# Issue Overview 
## Command to Reproduce the Issue
```
scanio to-html -i /Users/shikari/.scanio/tmp/vcs.domain/project_name/repo_name/scanio-pr-tmp/121/scanio-report-semgrep.sarif -o /Users/shikari/.scanio/tmp/vcs.domain/project_name/repo_name/scanio-pr-tmp/121/scanio-report-semgrep.html -s /Users/shikari/.scanio/tmp/vcs.domain/project_name/repo_name/scanio-pr-tmp/121
```

Before executing this command, I fetched a diff from the PR (only changed code) and scanned it using Semgrep, which generated a SARIF report.

## Issue Description
The command incorrectly joins paths when generating the final HTML report, causing the directory path ```/Users/shikari/.scanio/tmp/vcs.domain/project_name/repo_name/scanio-pr-tmp/121``` to appear twice:
- The method for joining ```r.sourceFolder``` and ```*loc.ArtifactLocation.URI``` does not account for the presence of absolute paths in the SARIF report.
- In a CI environment like Jenkins for PR scans, the report includes absolute paths that are not meaningful to the developer who created the PR.

# Relevant Code
https://github.com/scan-io-git/scan-io/blob/b0338caccc97859f4f582309c3c0e47f60ec4081/internal/sarif/sarif.go#L176

```PhysicalLocation``` ->```*loc.ArtifactLocation.URI``` contains an absolute path in my case, leading to:
```/Users/shikari/.scanio/tmp/vcs.domain/project_name/repo_name/scanio-pr-tmp/121/Users/shikari/.scanio/tmp/vcs.domain/project_name/repo_name/scanio-pr-tmp/121/vendor/github.com/lib/pq/ssl.go```

⚠️ Semgrep SARIF contains absolute paths, but this behavior could differ with other scanners. For instance, Trufflehog3 reports only include relative paths in a JSON format.

The following error occurs due to incorrect file path handling:
```
[DEBUG] core: can't read source file: err="failed to open file: open /Users/shikari/.scanio/tmp/vcs.domain/project_name/repo_name/scanio-pr-tmp/121/Users/shikari/.scanio/tmp/vcs.domain/project_name/repo_name/scanio-pr-tmp/121/vendor/github.com/lib/pq/ssl.go: no such file or directory"
```

As a result, the final report lacks links to specific issue regions within the file.

# Suggested Improvement
Consider whether absolute paths are necessary in the report, especially for local scans not run in CI mode. 
A potential solution is to trim the string from the ```-s``` argument out of the final report's ```*loc.ArtifactLocation.URI``` and avoid concatenating it with ```r.sourceFolder ```in CI mode.

ℹ️ Attached Files: SARIF report and HTML report examples are provided for further reference.
[example.zip](https://github.com/user-attachments/files/16632931/example.zip)

**Comment by japroc** [comment]
Steps to reproduce:
```bash
vagrant@vagrant:/tmp$ git clone https://github.com/juice-shop/juice-shop.git
vagrant@vagrant:/tmp$ cd juice-shop/
vagrant@vagrant:/tmp/juice-shop$ git remote rm origin
vagrant@vagrant:/tmp/juice-shop$ git remote add origin git@github.com:juice-shop/juice-shop.git
vagrant@vagrant:/tmp/juice-shop$ cd /vagrant/
vagrant@vagrant:/vagrant$ scanio analyse --scanner semgrep /tmp/juice-shop/ --format sarif --output /tmp/juice-shop/semgrep_results.sarif
vagrant@vagrant:/vagrant$ scanio to-html -i /tmp/juice-shop/semgrep_results.sarif -o /tmp/juice-shop/semgrep_results.html -s /tmp/juice-shop/
```
![Screenshot 2024-08-16 202505](https://github.com/user-attachments/assets/ed087a1d-c070-428d-974a-c52c67841abe)
